version: 2.1

jobs:
  container-agent:
    docker:
      - image: krallin/ubuntu-tini
        #entrypoint: ["/usr/bin/tini", "-c"]
    resource_class: logan/container-runner
    steps:
      - run:
          name: Who is PID 1?
          command: ps -p 1 -o comm=

workflows:
  container-agent:
    jobs:
      - container-agent
