version: 2.1

jobs:
  container-agent:
    docker:
      - image: cimg/base:current
    parallelism: 40
    resource_class: logan/gcp-ci-runner
    steps:
      - checkout
      - run: echo "Hello!"

workflows:
  container-agent:
    jobs:
      - container-agent
