version: 2.1

jobs:
  container-agent:
    docker:
      - image: cimg/base:current
    parallelism: 20
    resource_class: logan/gcp-ci-runner
    steps:
      - checkout
      - run: echo "Hello!"
      - run: sleep 300

workflows:
  container-agent:
    jobs:
      - container-agent
